
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_ERROR = 'SET_CURRENT_USER_ERROR';

export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAILURE = 'GET_COMPANY_FAILURE';

export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const GET_COMPANIES_FAILURE = 'GET_COMPANIES_FAILURE';

export const ADD_COMPANY_SUCCESS = 'ADD_COMPANY_SUCCESS';
export const ADD_COMPANY_FAILURE = 'ADD_COMPANY_FAILURE';

export const EDIT_COMPANY_SUCESS = 'EDIT_COMPANY_SUCCESS';
export const EDIT_COMPANY_SUCESS_FAILURE = 'EDIT_COMPANY_SUCCESS_FAILURE';

export const ADD_CERTIFICATE_SUCCESS = 'ADD_CERTIFICATE_SUCCESS';
export const ADD_CERTIFICATE_FAILURE = 'ADD_CERTIFICATE_FAILURE';
